"""Add hours_worked and salary_paid to EmployeeProfile

Revision ID: 7d8c872d738f
Revises: e119384d3bc9
Create Date: 2025-04-23 20:18:46.533657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8c872d738f'
down_revision = 'e119384d3bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emergency', schema=None) as batch_op:
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_emergency_employee', 'employee_profile', ['assigned_employee_id'], ['id'])

    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_worked', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('salary_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_profile', schema=None) as batch_op:
        batch_op.drop_column('salary_paid')
        batch_op.drop_column('hours_worked')

    with op.batch_alter_table('emergency', schema=None) as batch_op:
        #batch_op.drop_constraint('fk_emergency_employee', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['assigned_employee_id'], ['id'])

    # ### end Alembic commands ###
